spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe_hub?serverTimeZone=UTC
    username: root
    password:

  tomcat:
    test-on-borrow: true
    validation-query: SELECT 1
    connection-properties: useUnicode=true;characterEncoding=utf-8