spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  tomcat:
    test-on-borrow: true
    validation-query: SELECT 1
    connection-properties: useUnicode=true;characterEncoding=utf-8